### ISSUE TITLE
Not an issue, but I don't know how else to report this

### ISSUE THREAD

**Issue by skironDotNet** [nighthawk-apps/nighthawk-ios-wallet#20]
For Android wallet 2.0 repository, there is not "Issues" tab available, so I created a feature under "no longer maintained" android wallet. Yet the feature target both the iOS and Android because it's a philosophical feature platform neutral

**Comment by tw0po1nt** [comment]
@nighthawk24 Can you please similarly enable issues on the Android repo as you did for the iOS one?

**Comment by nighthawk24** [comment]
Thank you for bringing this to our attention @skironDotNet 

Issues are opened up on both [nighthawk-android-walle](https://github.com/nighthawk-apps/nighthawk-android-wallet)t and [nighthawk-ios-wallet](https://github.com/nighthawk-apps/nighthawk-ios-wallet) repos.
